

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="description" content="Online MDISK Link Streamer">

    <meta name="author" content="Extra Tv Team ">

    <meta name="copyright" content="Created by Extra Tv Team">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" type="image/x-icon" href="https://i.imgur.com/tRpk0ay.jpg">

    <title>MDISK LINK STREAMER</title>

    <link rel="stylesheet" href="https://snehmdisk.netlify.app/data/style.css">

    <link rel="stylesheet" href="https://snehmdisk.netlify.app/data/style1.css">

    <style>

        body {

            background-color: #131438;

        }

    </style>

</head>

<body>

    <p align="center"><img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjtuP-VTpNsS-OvzCe_0sIY5-gfjznTxu3SSX1xFBaSidxejKXt-tAfQwDNtsQIZA8rtRVvhcATSUP1am6qqk0jT0uA7XjD448qBf8QgeZr3P0EB0iwdwqLDJLyqPyXWKn-OeQTbaLE3ad8pUbDu0wmRUBF373TyN3RSAgvb_6v3UGyA21YZRk-MbTJgg/s646/Picsart_22-11-12_17-13-59-801.png" height="50px" width="300px" alt="MDisk"></p>

    <h1 style="color:red; text-align:center; cursor: pointer;"><a href="https://ttttt.me/Extra_Tv_IPTV_m3u8_link">MDISK LINK

            STREAMER</a></h1>

    <br>

    <h3 style="text-align: center; color: #ff0037; font-family: 'Balsamiq Sans', cursive; font-size: 17px;">✍️ ENTER

        UR MDISK URL BELOW 🍃 <br>& 🎭 CLICK ON STREAM</h3><br><br><br>

    <div>

        <form method="get" action="https://snehmdisk.mitthu.workers.dev" _lpchecked="1">

            <center>

                <div class="bar">

                    <input type="search" class="searchbar" name="url" value="" placeholder="Enter MDisk URL"

                        autocomplete="off">

                    <a href=""> <img class="zee5" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhj1i9pHNWT-rkqfn2357ba8M1vtSIKqZErlWBq_BVW1HT2cMq04cFuHgDufcPMh5ZGqIVcGy9DTTcTIKAXtgJxksI7pBEmvNSi-H7ohYTQ4LFVhuG_gKCsLPhKzYt6SLemshz-Bjw30KXXZs9fAg2_edCr_l2ZnHPNGIk2ZWYwyHP8txEDYPwlAJ6Tiw/s415/Picsart_22-11-12_18-29-15-035.png" width="23px" title="Go To MDisk Site"></a>

                </div>

                <button class="button" type="submit" value="" title="Stream And Enjoy !!">

                  
                    Stream

                </button>

                <br>

                <p style="color:rgb(255, 0, 0); text-align:center;font-family: 'Corben', cursive;">Use This Pattern Link

                    <br>

                    <code style="color:white;">https://mdisk.me/convertor/640x267/641wAe</code>

                </p>

                <footer class="footer">

                    <div class="container">

                        <span class="copyright"><a style="text-decoration: none; color: #1b6be3;" href="/">© 2022-23

                                Extra Team</a></span>

                    </div>

                </footer>

</body>

</html>
